### ISSUE TITLE
Fix Confusing Error Config (ReturnErrors=True)

### ISSUE THREAD

**Issue by artbrock** [Holochain/holochain-proto#588]
The system always returns errors. I think it would be MUCH CLEARER if we said: ThrowErrors=False rather than ReturnErrors=True

Please consider this change so the config setting is understandable.

**Comment by zippy** [comment]
The issue with this is that structuarlly golang's default value is false.  So if we want the default to throw errors, this is a pain.  Instead, I'm going to do this:  The configuration attribute will be:  `ErrorHandling` and it will be a string which will either be:  "throw_errors" or "return_error_value", and if the value of `ErrorHandling` `""` then I will set it to "throw_errors"

**Comment by philipbeadle** [comment]
Thoughts, given we are super alpha how about we just throw errors?  We needed this switch to stop errors when a getLinks was empty, which is fixed now.  Just need it for get(hash) and then maybe we dont need this switch anymore?

**Comment by zippy** [comment]
Not quite sure what you mean here.  I know that I've had conversations with people about their preferred style of error handling, and that people differ between wanting to catch thrown errors, or check returned errors.  The idea here is to give a configuration option so the app dev can choose.  But are you talking about which to set as default?    I think @rayzer42 was worried that if we don't throw errors app devs are likely to make more mistakes because then the errors are more likely to go unnoticed.

**Comment by philipbeadle** [comment]
Yes we should throw errors :) But not if its not an error.  Having no entry for a hash is not an error nor is having no links for a query, they are just empty.
