### ISSUE TITLE
New error format needs to be in Err of tests

### ISSUE THREAD

**Issue by philipbeadle** [Holochain/holochain-proto#603]
Expected error:	Validation Failed
	Got error:		{"errorMessage":"Validation Failed","function":"update","name":"HolochainError","source":{"column":"15","functionName":"postMod","line":"172"}}

I'd like to be able to use 
"Err": "Validation Failed"

**Comment by zippy** [comment]
So there's two things here.  I do think we want a way to get the whole error object because we are likely to allow other properties into it that we may want to test against.  So what I will do is add an  "ErrorMsg" attribute that you can use to test against if all you want is to test against the Message
