### ISSUE TITLE
Get environment varialbles/config settings into developer docs

### ISSUE THREAD

**Issue by artbrock** [holochain/holochain-proto#607]
I'm trying to collect up the environment variables to put them into the dev docs and have some questions before proceeding. The Go code makes it seem like we are sometimes using/expecting numbers and sometimes using/expecting boolean true/false values... 

HCLOG_APP_ENABLE=0
HCLOG_DHT_ENABLE=1
HCLOG_GOSSIP_ENABLE=true
HCLOG_PREFIX="a prefix:"9
HCLOG_DEBUG_ENABLE= ????

HC_DEFAULT_BOOTSTRAPSERVER= ???
HC_DEFAULT_ENABLEMDNS= ???
HC_DEFAULT_ENABLENATUPNP= ???

Potential conflicting(?) format for:
HOLOCHAINCONFIG_ENABLEMDNS
HOLOCHAINCONFIG_BOOTSTRAP
HOLOCHAINCONFIG_PORT
HOLOCHAINCONFIG_ENABLENATUPNP

**Comment by artbrock** [comment]
I probably need some clarifications, but have started documenting this here:  http://developer.holochain.org/Command_line_tools

**Comment by zippy** [comment]
For HCLOG_X_ENABLE you can use either 1/0 or true/false I made them both work.
HOLOCHAINCONFIG_* are a special case (which is why different format).  They are used to make different default values to be used when the config file is created by hcdev for tests or scenarios when the .holochain_dev directories are made.   HC_DEFAULT_* works all the time (hcdev & hcd) and the idea is that a person might want to set them as their preference.
HC_DEFAULT_BOOTSTRAPSERVER=domain.com/ipaddress
HC_DEFAULT_ENABLEMDNS=true/false

**Comment by zippy** [comment]
Moved to Org repo
